Algoritmo "estrutura de repeticao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernada Nalon
// Descrição   : ordem descrescente
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 
 i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    i <-100
   repita
   escreva (i)
   i <- i - 1
   ate i < 1
   

Fimalgoritmo