Algoritmo "estrutura de repeticao"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : contagem crescente
// Autor(a)    : Arilton Souza
// Data atual  : 11/12/2024
Var
// Seção de Declarações das variáveis 
i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   i <-1
   repita
   escreva (i)
   i <- i + 1
   ate i > 10
   

Fimalgoritmo