Algoritmo "laco de repeticao enquanto 10a1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Fernanda Nalon
// Descrição   : ordem decrescente de 10 a 1
// Autor(a)    : Arilton Souza
// Data atual  : 12/12/2024
Var
// Seção de Declarações das variáveis 
   i: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
     i <- 10


    enquanto i >= 1 faça
        escreva(i, " ")
        i <- i - 1
    fimEnquanto

Fimalgoritmo